package cs3500.pa03;

import static org.junit.jupiter.api.Assertions.assertEquals;

import cs3500.pa03.controller.BattleSalvoController;
import cs3500.pa03.model.AiPlayer;
import cs3500.pa03.model.ManualPlayer;
import cs3500.pa03.model.Player;
import java.io.StringReader;
import java.util.Random;
import java.util.Scanner;
import org.junit.jupiter.api.Test;

/**
 * Represents tests for the BattleSalvoController class.
 */
class BattleSalvoControllerTest {
  private BattleSalvoController bsc;
  private StringBuilder sb;
  private StringReader sr;
  Player p1;
  Player p2;

  /**
   * Tests the entire game by putting in sample input of a game where the console player wins and
   * checks that it outputs the appropriate messages and boards as the game progresses.
   */
  @Test
  public void testStartGameManualPlayerWins() {
    sr = new StringReader("twelve 1\n6\n7 8 10\n3 10\n12 4\n3 4\n6 7\n7 1 9 2 4\n3 1 2 1\n"
        + "3 0 2 1\n2 1 1 2\n3 four\n2 4 6\n-4 3\n0 -3\n0 12\n14 9\n14 20\n16 2\n0 3\n4 6\n0 3"
        + "\n6 5\n2 4\n5 1\n4 2\n2 0\n1 3\n2 1\n2 2\n2 3\n5 2\n5 3\n1 2\n3 2\n6 2\n0 2\n3 4\n4 4"
        + "\n0 5\n1 5\n1 4\n5 4\n6 4\n0 4\n3 1\n4 1\n6 1\n6 3\n6 0\n2 5\n3 5\n4 5\n5 5\n3 3\n0 1"
        + "\n1 1\n4 3\n3 0\n4 0\n5 0\n");
    Scanner s = new Scanner(sr);
    sb = new StringBuilder();

    p1 = new ManualPlayer("Nina", new Random(4), s, sb);
    p2 = new AiPlayer("AI Player", new Random(6));

    bsc = new BattleSalvoController(s,
        sb, p1, p2);

    bsc.startGame();

    assertEquals(
        "Hello! Welcome to the OOD BattleSalvo Game!\n"
            + "Please enter a valid height and width below:\n"
            + "Uh Oh! You've entered invalid dimensions. Please remember that the height and width "
            + "of the game must be in the range [6, 15], inclusive. Try again!\n"
            + "Uh Oh! You've entered invalid dimensions. Please remember that the height and width "
            + "of the game must be in the range [6, 15], inclusive. Try again!\n"
            + "Uh Oh! You've entered invalid dimensions. Please remember that the height and width "
            + "of the game must be in the range [6, 15], inclusive. Try again!\n"
            + "Uh Oh! You've entered invalid dimensions. Please remember that the height and width "
            + "of the game must be in the range [6, 15], inclusive. Try again!\n"
            + "Uh Oh! You've entered invalid dimensions. Please remember that the height and width "
            + "of the game must be in the range [6, 15], inclusive. Try again!\n"
            + "Uh Oh! You've entered invalid dimensions. Please remember that the height and width "
            + "of the game must be in the range [6, 15], inclusive. Try again!\n"
            + "Please enter your fleet in the order [Carrier, Battleship, Destroyer, Submarine].\n"
            + "Remember, your fleet may not exceed size 6.\n"
            + "Uh Oh! You've entered invalid fleet sizes.\n"
            + "Please enter your fleet in the order [Carrier, Battleship, Destroyer, Submarine].\n"
            + "Remember, your fleet may not exceed size 6.\n"
            + "Uh Oh! You've entered invalid fleet sizes.\n"
            + "Please enter your fleet in the order [Carrier, Battleship, Destroyer, Submarine].\n"
            + "Remember, your fleet may not exceed size 6.\n"
            + "Uh Oh! You've entered invalid fleet sizes.\n"
            + "Please enter your fleet in the order [Carrier, Battleship, Destroyer, Submarine].\n"
            + "Remember, your fleet may not exceed size 6.\n"
            + "Opponent Board Data:\n"
            + "0 0 0 0 0 0 0 \n"
            + "0 0 0 0 0 0 0 \n"
            + "0 0 0 0 0 0 0 \n"
            + "0 0 0 0 0 0 0 \n"
            + "0 0 0 0 0 0 0 \n"
            + "0 0 0 0 0 0 0 \n"
            + "Your Initial Board:\n"
            + "S S S 0 0 0 0 \n"
            + "0 0 B B B B B \n"
            + "0 C C C C C C \n"
            + "S 0 0 0 0 0 0 \n"
            + "S C C C C C C \n"
            + "S 0 D D D D 0 \n"
            + "Opponent Board Data:\n"
            + "0 0 0 0 0 0 0 \n"
            + "0 0 0 0 0 0 0 \n"
            + "0 0 0 0 0 0 0 \n"
            + "0 0 0 0 0 0 0 \n"
            + "0 0 0 0 0 0 0 \n"
            + "0 0 0 0 0 0 0 \n"
            + "Your Board:\n"
            + "X X X 0 0 0 0 \n"
            + "0 0 X X X X X \n"
            + "0 X X X X X X \n"
            + "X 0 0 0 0 0 0 \n"
            + "X X X X X X X \n"
            + "X 0 X X X X 0 \n"
            + "Please Enter 6 Shots:\n"
            + "Uh Oh! You've entered an invalid salvo.\n"
            + "Please Enter 6 Shots:\n"
            + "Uh Oh! You've entered an invalid salvo.\n"
            + "Please Enter 6 Shots:\n"
            + "Uh Oh! You've entered an invalid salvo.\n"
            + "Please Enter 6 Shots:\n"
            + "Uh Oh! You've entered an invalid salvo.\n"
            + "Please Enter 6 Shots:\n"
            + "Uh Oh! You've entered an invalid salvo.\n"
            + "Please Enter 6 Shots:\n"
            + "Uh Oh! You've entered an invalid salvo.\n"
            + "Please Enter 6 Shots:\n"
            + "Uh Oh! You've entered an invalid salvo.\n"
            + "Please Enter 6 Shots:\n"
            + "Uh Oh! You've entered an invalid salvo.\n"
            + "Please Enter 6 Shots:\n"
            + "Uh Oh! You've entered an invalid salvo.\n"
            + "Please Enter 6 Shots:\n"
            + "Opponent Board Data:\n"
            + "0 0 H 0 0 0 0 \n"
            + "0 0 0 0 0 M 0 \n"
            + "0 0 0 0 H 0 0 \n"
            + "H 0 0 0 0 0 0 \n"
            + "0 0 H 0 0 0 0 \n"
            + "0 0 0 0 0 0 M \n"
            + "Your Board:\n"
            + "X X X 0 0 0 0 \n"
            + "0 M X X X X H \n"
            + "M X H X X X X \n"
            + "X 0 0 0 0 0 0 \n"
            + "X X X H X X X \n"
            + "X 0 X X X H 0 \n"
            + "Please Enter 6 Shots:\n"
            + "Opponent Board Data:\n"
            + "0 0 H 0 0 0 0 \n"
            + "0 0 H 0 0 M 0 \n"
            + "0 0 H 0 H H 0 \n"
            + "H H H 0 0 H 0 \n"
            + "0 0 H 0 0 0 0 \n"
            + "0 0 0 0 0 0 M \n"
            + "Your Board:\n"
            + "H X X M 0 M 0 \n"
            + "0 M X X X X H \n"
            + "M X H X X X X \n"
            + "H 0 0 0 M 0 0 \n"
            + "X X X H X X X \n"
            + "X 0 H X X H 0 \n"
            + "Please Enter 6 Shots:\n"
            + "Opponent Board Data:\n"
            + "0 0 H 0 0 0 0 \n"
            + "0 0 H 0 0 M 0 \n"
            + "M H H H H H H \n"
            + "H H H 0 0 H 0 \n"
            + "0 0 H H H 0 0 \n"
            + "0 0 0 0 0 0 M \n"
            + "Your Board:\n"
            + "H X X M 0 M 0 \n"
            + "0 M X X X X H \n"
            + "M H H X H X X \n"
            + "H 0 M 0 M 0 M \n"
            + "X H X H X X X \n"
            + "H 0 H X X H 0 \n"
            + "Please Enter 6 Shots:\n"
            + "Opponent Board Data:\n"
            + "0 0 H 0 0 0 0 \n"
            + "0 0 H 0 0 M 0 \n"
            + "M H H H H H H \n"
            + "H H H 0 0 H 0 \n"
            + "M M H H H H M \n"
            + "M M 0 0 0 0 M \n"
            + "Your Board:\n"
            + "H X X M 0 M 0 \n"
            + "0 M X X H X H \n"
            + "M H H X H X H \n"
            + "H M M 0 M 0 M \n"
            + "X H X H X X X \n"
            + "H M H H X H 0 \n"
            + "Please Enter 5 Shots:\n"
            + "Opponent Board Data:\n"
            + "0 0 H 0 0 0 M \n"
            + "0 0 H H H M M \n"
            + "M H H H H H H \n"
            + "H H H 0 0 H M \n"
            + "M M H H H H M \n"
            + "M M 0 0 0 0 M \n"
            + "Your Board:\n"
            + "H X X M 0 M 0 \n"
            + "0 M H H H H H \n"
            + "M H H X H X H \n"
            + "H M M 0 M 0 M \n"
            + "X H X H X X H \n"
            + "H M H H X H 0 \n"
            + "Please Enter 5 Shots:\n"
            + "Opponent Board Data:\n"
            + "0 0 H 0 0 0 M \n"
            + "0 0 H H H M M \n"
            + "M H H H H H H \n"
            + "H H H H 0 H M \n"
            + "M M H H H H M \n"
            + "M M M H H H M \n"
            + "Your Board:\n"
            + "H X H M M M 0 \n"
            + "0 M H H H H H \n"
            + "M H H H H X H \n"
            + "H M M M M 0 M \n"
            + "X H X H X X H \n"
            + "H M H H X H 0 \n"
            + "Please Enter 3 Shots:\n"
            + "Opponent Board Data:\n"
            + "0 0 H 0 0 0 M \n"
            + "H H H H H M M \n"
            + "M H H H H H H \n"
            + "H H H H H H M \n"
            + "M M H H H H M \n"
            + "M M M H H H M \n"
            + "Your Board:\n"
            + "H H H M M M 0 \n"
            + "0 M H H H H H \n"
            + "M H H H H H H \n"
            + "H M M M M 0 M \n"
            + "X H X H H X H \n"
            + "H M H H X H 0 \n"
            + "Please Enter 3 Shots:\n"
            + "The game is over!\n"
            + "Nina wins!\n", sb.toString());
  }

  /**
   * Tests the entire game by putting in sample input of a game where the AI player wins and
   * checks that it outputs the appropriate messages and boards as the game progresses.
   */
  @Test
  public void testStartGameAiPlayerWins() {
    sr = new StringReader("6 7\n2 1 1 2\n0 0\n0 1\n1 0\n3 5\n6 2\n6 5\n3 4\n4 2\n2 3\n5 0\n"
        + "4 1\n4 4\n0 2\n0 3\n0 4\n0 5\n2 0\n3 0\n4 0\n6 0\n6 1\n5 1\n5 2\n5 3\n6 3\n6 4\n1 5"
        + "\n1 4\n2 5\n3 1\n3 2\n4 5\n1 1\n5 4\n");
    Scanner s = new Scanner(sr);
    sb = new StringBuilder();

    p1 = new ManualPlayer("Nina", new Random(4), s, sb);
    p2 = new AiPlayer("AI Player", new Random(6));

    bsc = new BattleSalvoController(s,
        sb, p1, p2);

    bsc.startGame();

    assertEquals(
        "Hello! Welcome to the OOD BattleSalvo Game!\n"
            + "Please enter a valid height and width below:\n"
            + "Please enter your fleet in the order [Carrier, Battleship, Destroyer, Submarine].\n"
            + "Remember, your fleet may not exceed size 6.\n"
            + "Opponent Board Data:\n"
            + "0 0 0 0 0 0 0 \n"
            + "0 0 0 0 0 0 0 \n"
            + "0 0 0 0 0 0 0 \n"
            + "0 0 0 0 0 0 0 \n"
            + "0 0 0 0 0 0 0 \n"
            + "0 0 0 0 0 0 0 \n"
            + "Your Initial Board:\n"
            + "S S S 0 0 0 0 \n"
            + "0 0 B B B B B \n"
            + "0 C C C C C C \n"
            + "S 0 0 0 0 0 0 \n"
            + "S C C C C C C \n"
            + "S 0 D D D D 0 \n"
            + "Opponent Board Data:\n"
            + "0 0 0 0 0 0 0 \n"
            + "0 0 0 0 0 0 0 \n"
            + "0 0 0 0 0 0 0 \n"
            + "0 0 0 0 0 0 0 \n"
            + "0 0 0 0 0 0 0 \n"
            + "0 0 0 0 0 0 0 \n"
            + "Your Board:\n"
            + "X X X 0 0 0 0 \n"
            + "0 0 X X X X X \n"
            + "0 X X X X X X \n"
            + "X 0 0 0 0 0 0 \n"
            + "X X X X X X X \n"
            + "X 0 X X X X 0 \n"
            + "Please Enter 6 Shots:\n"
            + "Opponent Board Data:\n"
            + "M M 0 0 0 0 0 \n"
            + "H 0 0 0 0 0 0 \n"
            + "0 0 0 0 0 0 H \n"
            + "0 0 0 0 0 0 0 \n"
            + "0 0 0 0 0 0 0 \n"
            + "0 0 0 H 0 0 M \n"
            + "Your Board:\n"
            + "X X X 0 0 0 0 \n"
            + "0 M X X X X H \n"
            + "M X H X X X X \n"
            + "X 0 0 0 0 0 0 \n"
            + "X X X H X X X \n"
            + "X 0 X X X H 0 \n"
            + "Please Enter 6 Shots:\n"
            + "Opponent Board Data:\n"
            + "M M 0 0 0 M 0 \n"
            + "H 0 0 0 H 0 0 \n"
            + "0 0 0 0 H 0 H \n"
            + "0 0 H 0 0 0 0 \n"
            + "0 0 0 H H 0 0 \n"
            + "0 0 0 H 0 0 M \n"
            + "Your Board:\n"
            + "H X X M 0 M 0 \n"
            + "0 M X X X X H \n"
            + "M X H X X X X \n"
            + "H 0 0 0 M 0 0 \n"
            + "X X X H X X X \n"
            + "X 0 H X X H 0 \n"
            + "Please Enter 6 Shots:\n"
            + "Opponent Board Data:\n"
            + "M M H H 0 M 0 \n"
            + "H 0 0 0 H 0 0 \n"
            + "M 0 0 0 H 0 H \n"
            + "H 0 H 0 0 0 0 \n"
            + "M 0 0 H H 0 0 \n"
            + "M 0 0 H 0 0 M \n"
            + "Your Board:\n"
            + "H X X M 0 M 0 \n"
            + "0 M X X X X H \n"
            + "M H H X H X X \n"
            + "H 0 M 0 M 0 M \n"
            + "X H X H X X X \n"
            + "H 0 H X X H 0 \n"
            + "Please Enter 6 Shots:\n"
            + "Opponent Board Data:\n"
            + "M M H H H M M \n"
            + "H 0 0 0 H M M \n"
            + "M 0 0 0 H H H \n"
            + "H 0 H 0 0 H 0 \n"
            + "M 0 0 H H 0 0 \n"
            + "M 0 0 H 0 0 M \n"
            + "Your Board:\n"
            + "H X X M 0 M 0 \n"
            + "0 M X X H H H \n"
            + "M H H X H X H \n"
            + "H M M 0 M 0 M \n"
            + "X H X H X X X \n"
            + "H M H H X H 0 \n"
            + "Please Enter 5 Shots:\n"
            + "Opponent Board Data:\n"
            + "M M H H H M M \n"
            + "H 0 0 0 H M M \n"
            + "M 0 0 0 H H H \n"
            + "H 0 H 0 0 H M \n"
            + "M M 0 H H 0 M \n"
            + "M M M H 0 0 M \n"
            + "Your Board:\n"
            + "H X X M M M 0 \n"
            + "0 M H H H H H \n"
            + "M H H H H X H \n"
            + "H M M 0 M 0 M \n"
            + "X H X H X X H \n"
            + "H M H H X H 0 \n"
            + "Please Enter 3 Shots:\n"
            + "Opponent Board Data:\n"
            + "M M H H H M M \n"
            + "H 0 0 H H M M \n"
            + "M 0 0 H H H H \n"
            + "H 0 H 0 0 H M \n"
            + "M M 0 H H 0 M \n"
            + "M M M H H 0 M \n"
            + "Your Board:\n"
            + "H H H M M M 0 \n"
            + "0 M H H H H H \n"
            + "M H H H H H H \n"
            + "H M M M M 0 M \n"
            + "X H X H H X H \n"
            + "H M H H X H 0 \n"
            + "Please Enter 2 Shots:\n"
            + "Opponent Board Data:\n"
            + "M M H H H M M \n"
            + "H H 0 H H M M \n"
            + "M 0 0 H H H H \n"
            + "H 0 H 0 0 H M \n"
            + "M M 0 H H H M \n"
            + "M M M H H 0 M \n"
            + "Your Board:\n"
            + "H H H M M M M \n"
            + "0 M H H H H H \n"
            + "M H H H H H H \n"
            + "H M M M M M M \n"
            + "X H X H H H H \n"
            + "H M H H H H M \n"
            + "Please Enter 0 Shots:\n"
            + "The game is over!\n"
            + "AI Player wins!\n", sb.toString());
  }
}